name = "BilevelHeuristics"
uuid = "61682c44-1689-4c10-8e1b-162e0db5231e"
authors = ["Jesus Mejia <jesusmejded@gmail.com>"]
version = "0.1.4"

[deps]
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLKernels = "6899632a-1081-549c-8d71-752c8a25a7ba"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
LineSearches = "7.1.1"
MLKernels = "0.4.0"
Metaheuristics = "3.2.9"
Optim = "1.6.1"
Reexport = "1.2.2"
UnicodePlots = "2.6.0"
julia = "^1.6"
